import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Alexandria } from "next/font/google";

const alexandria = Alexandria({ weight: "variable", subsets: ["latin"] });
export const metadata: Metadata = {
  title: "nexail",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={alexandria.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
